### PR TITLE
created the hero section from scratch

### LINKED ISSUE #3: Create Hero Section
image
Kindly refer #1 for the community logo
You can refer the figma file for colors, fonts etc.

Image in this section:
cerritus_coders

### PR DESCRIPTION
**Pull request by ishir21**
Created the entire hero section and also added shadow in navbar

### CODE REVIEW

**Comment by cdhiraj40** [comment]
@ishir21 Try using only one package manager and I would recommend using `yarn`. Please delete `package-lock.json` file.

**Comment by cdhiraj40** [comment]
Also, when checking the deployment it shows the line way longer than it should be!
image

Along with that, the cerritus coder logo(bigger one) in the hero section is in the center while it should be right aligned. Just the same way cerritus collage is left aligned.

**Comment by ishir21** [comment]
Also I have not added responsiveness, will do that later

**Comment by ishir21** [comment]
@cdhiraj40

**Review by cdhiraj40 — APPROVED** [review]
Just change the alignment of the logo and you are good to go. Ready to merge 🎉

**Pull request merged**
