### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by ConnectBhawna**

### CODE REVIEW

**Comment by pixawna** [comment]
Added the footer

**Comment by ishir21** [comment]
@Bhawna1203 also add the socials in the footer.
You can use this https://daisyui.com/components/footer/

**Comment by pixawna** [comment]
okk done with this part
But i think it doesn't make any sense of including social link as we already mentioned the socials in the connect session

**Comment by ishir21** [comment]
Just checked the files, add the footer under components, so that we will be able to reuse it

**Comment by cdhiraj40** [comment]
hey @Bhawna1203 do you mind updating this PR, it has merge conflicts.

**Pull request closed without merging**
